services:
  web:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: webhack-lab-web
    container_name: webhack-web
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_NAME: ${DB_NAME:-locth_lab}
      DB_USER: ${DB_USER:-labuser}
      DB_PASS: ${DB_PASS:-labpass}
      APP_ENV: docker
    volumes:
      - ./public:/var/www/html:rw
      - ./flags:/var/www/flags:ro
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: webhack-db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB_NAME:-locth_lab}
      MYSQL_USER: ${DB_USER:-labuser}
      MYSQL_PASSWORD: ${DB_PASS:-labpass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS:-rootpass}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${DB_ROOT_PASS:-rootpass} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30

  pma:
    image: phpmyadmin:5-apache
    container_name: webhack-pma
    env_file:
      - .env
    environment:
      PMA_HOST: db
      PMA_USER: ${DB_USER:-labuser}
      PMA_PASSWORD: ${DB_PASS:-labpass}
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
